apiVersion: v1
data:
  aes256-sharesecret-1.txt: NUE3NDYwQUIxNzgyNDk3OThGNEFDRTU4NDZGOTlFOURCMENBMjg2RTMwOUY2QkFBRjdDMDNCREMxMkNCMjU2Mwo=
kind: Secret
metadata:
  creationTimestamp: null
  name: booking-service-secret3
  namespace: dp01-dev
