apiVersion: v1
data:
  aes256-sharesecret-1.txt: QTUxMkMyODZCQkUxMDE2Njk1MTNCRDNFMTAyMTY4NUE4N0VCMDk2MjUzN0YxODkwRkI1MkY3QjJBNzkxNDAxMAo=
kind: Secret
metadata:
  creationTimestamp: null
  name: booking-service-secret3
  namespace: dp01-dev
